---
ocp4_days_workload_ztwim_namespace: openshift-zero-trust-workload-identity-manager
ocp4_days_workload_ztwim_channel: stable-v1
ocp4_days_workload_ztwim_package: openshift-zero-trust-workload-identity-manager
ocp4_days_workload_ztwim_automatic_install_plan_approval: true
ocp4_days_workload_ztwim_use_catalog_snapshot: false
