---
- name: Prune unused container images from nodes (final pass)
  when: ACTION == "provision"
  ansible.builtin.include_role:
    name: openshift_days.ops_track.ocp4_workload_node_image_prune

- name: Skip image prune on destroy
  when: ACTION == "destroy"
  debug:
    msg: "Skipping image prune on destroy"
